# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pypgavro

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          app_user: pypgavro
          app_user_password: pypgavro
          app_db: pypgavro
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest poetry
          poetry install
      - name: Lint with psf/black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./pypgavro"
          version: "22.3.0"
      - name: Test with pytest
        run: |
          poetry run pytest
